version: '3.8'

services:
  app:
    container_name: badminton_server_prod
    image: badminton_server_prod:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 8001:8001
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
      DB_HOST: pgsqldb
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      NODE_OPTIONS: --max-old-space-size=4096
      VIRTUAL_HOST: apiw.bstar-badminton.com
      LETSENCRYPT_HOST: apiw.bstar-badminton.com
    depends_on:
      - pgsqldb
      - redis
    restart: unless-stopped

  pgsqldb:
    container_name: badminton_prod_pgsqldb
    image: postgres:14.3
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - 5433:5432
    volumes:
      - badminton_prod_pgsqldata:/var/lib/postgresql/data

  redis:
    container_name: badminton_prod_redis
    restart: always
    image: redis:6.0-alpine
    ports:
      - '6380:6379'
    volumes:
      - badminton_prod_redis_data:/data

volumes:
  badminton_prod_redis_data:
  badminton_prod_pgsqldata:

networks:
  default:
    name: myapp
    external: true
